spring:
    application:
        name: SpringDataJPAHomework

    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        password: 29042003
        username: postgres

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true